export const movieGridColumns = [
  {
    field: "id",
    headerName: "#",
    width: 80,
    headerClass: "ag-right-aligned-header",
    cellStyle: { textAlign: "right" },
    cellClass: "ag-right-aligned-cell",
    sort: "desc",
  },
  {
    field: "title",
    headerName: "Title",
    minWidth: 200,
    flex: 1,
  },
  {
    field: "year",
    headerName: "Year",
    width: 150,
    resizable: false,
    headerClass: "ag-right-aligned-header",
    cellStyle: { textAlign: "right" },
    cellClass: "ag-right-aligned-cell",
  },
  {
    field: "director",
    headerName: "Director",
    width: 150,
  },
  {
    field: "rate",
    headerName: "Rate",
    width: 250,
    resizable: false,
    cellClass: "centered",
    cellRenderer: "MovieGridRateRenderer",
  },
  {
    field: "edit",
    headerName: "Edt.",
    width: 20,
    resizable: false,
    pinned: "right",
    cellRenderer: "GridUpdateRenderer",
  },
  {
    field: "remove",
    headerName: "Del.",
    width: 20,
    resizable: false,
    pinned: "right",
    cellRenderer: "GridRemovalRenderer",
  },
];
